; PlatformIO Project Configuration File
;
; QSPI XIP build: all .text/.rodata in QSPI (8MB)
; Bootloader vectors in internal FLASH (32KB)

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = stm32cube
build_flags = 
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Isrc/st7796
	-fomit-frame-pointer
	-DNDEBUG
	-DLV_USE_LOG=0
	-DLV_USE_ASSERT_NULL=0
	-DLV_USE_ASSERT_STYLE=0
	-DLV_USE_PERF_MONITOR=0
	-DLV_USE_MEM_MONITOR=0
board_build.ldscript = linker/STM32H750VBTX_QSPI.ld
upload_protocol = stlink
debug_tool = stlink
debug_init_break = tbreak main
debug_speed = 4000
lib_deps = lvgl/lvgl@^9.5.0
