; PlatformIO Project Configuration File
;
; QSPI XIP build: .text/.rodata in QSPI (8MB)
; ISR vectors in internal FLASH (32KB)
; .data/.bss in RAM_D1 (512KB AXI)

;[env:genericSTM32H750VB]
;platform = ststm32
;board = genericSTM32H750VB
;framework = stm32cube
;build_flags = 
;	-O2
;	-ffunction-sections
;	-fdata-sections
;	-Wl,--gc-sections
;	-Isrc/st7796
;	-fomit-frame-pointer
;	-DNDEBUG
;	-DSTM32H750xx
;	-DF_CPU=480000000L
;board_build.ldscript = linker/STM32H750VBTX_QSPI.ld
;upload_protocol = stlink
;debug_tool = stlink
;;debug_init_break = tbreak main
;debug_speed = 4000
;lib_deps = lvgl/lvgl@^9.5.0
;build_src_filter = +<*> -<.git/> -<.svn/>
;upload_speed = 115200

; Generate .bin from .elf after build
;extra_scripts_post = convert_to_bin.py

[env:weact_mini_h743vitx]
platform = ststm32
board = weact_mini_h743vitx
framework = stm32cube

; Оптимизация для размера
lib_deps = lvgl/lvgl@^9.5.0

build_flags = 
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Iinclude
	-Isrc/st7796
	-Isrc/measurement
	-I.pio/libdeps/weact_mini_h743vitx/lvgl
	-DUSBD_MAX_NUM_INTERFACES=1

board_build.ldscript = linker/STM32H743VIT_FLASH.ld
upload_protocol = stlink
debug_tool = stlink
debug_init_break = tbreak main
debug_speed = 4000

