; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = stm32cube
build_flags = 
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Isrc/st7796
    -fomit-frame-pointer
    -DNDEBUG
    -DLV_USE_LOG=0
    -DLV_USE_ASSERT_NULL=0
    -DLV_USE_ASSERT_STYLE=0
    -DLV_USE_PERF_MONITOR=0
    -DLV_USE_MEM_MONITOR=0
upload_protocol = stlink
board_build.ldscript = linker/STM32H750VBTX_FLASH.ld
debug_tool = stlink
debug_init_break = tbreak main
debug_speed = 4000
lib_deps = lvgl/lvgl@^9.5.0
