// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_ABOUT = NULL;
lv_obj_t * ui_statusBar6 = NULL;
lv_obj_t * ui_IconBuzzer6 = NULL;
lv_obj_t * ui_iconRS6 = NULL;
lv_obj_t * ui_iconNTP6 = NULL;
lv_obj_t * ui_iconWIFI6 = NULL;
lv_obj_t * ui_iconBT6 = NULL;
lv_obj_t * ui_PercentBaterry6 = NULL;
lv_obj_t * ui_Clock6 = NULL;
lv_obj_t * ui_iconBATERRY6 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Bar1 = NULL;
// event funtions
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuMain, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuMain_screen_init);
    }
}

void ui_event_Bar1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_Bar1, 1, LV_ANIM_ON);
    }
}

// build funtions

void ui_ABOUT_screen_init(void)
{
    ui_ABOUT = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ABOUT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusBar6 = lv_obj_create(ui_ABOUT);
    lv_obj_remove_style_all(ui_statusBar6);
    lv_obj_set_width(ui_statusBar6, 320);
    lv_obj_set_height(ui_statusBar6, 30);
    lv_obj_set_align(ui_statusBar6, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer6 = lv_image_create(ui_statusBar6);
    lv_obj_set_width(ui_IconBuzzer6, 20);
    lv_obj_set_height(ui_IconBuzzer6, 20);
    lv_obj_set_x(ui_IconBuzzer6, 136);
    lv_obj_set_y(ui_IconBuzzer6, 5);
    lv_obj_add_flag(ui_IconBuzzer6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer6, LV_IMAGE_ALIGN_TILE);

    ui_iconRS6 = lv_image_create(ui_statusBar6);
    lv_obj_set_width(ui_iconRS6, 20);
    lv_obj_set_height(ui_iconRS6, 20);
    lv_obj_set_x(ui_iconRS6, 10);
    lv_obj_set_y(ui_iconRS6, 0);
    lv_obj_set_align(ui_iconRS6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS6, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP6 = lv_image_create(ui_statusBar6);
    lv_obj_set_width(ui_iconNTP6, 20);
    lv_obj_set_height(ui_iconNTP6, 20);
    lv_obj_set_x(ui_iconNTP6, 34);
    lv_obj_set_y(ui_iconNTP6, 0);
    lv_obj_set_align(ui_iconNTP6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP6, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI6 = lv_image_create(ui_statusBar6);
    lv_obj_set_width(ui_iconWIFI6, 20);
    lv_obj_set_height(ui_iconWIFI6, 20);
    lv_obj_set_x(ui_iconWIFI6, 58);
    lv_obj_set_y(ui_iconWIFI6, 0);
    lv_obj_set_align(ui_iconWIFI6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI6, LV_IMAGE_ALIGN_TILE);

    ui_iconBT6 = lv_image_create(ui_statusBar6);
    lv_obj_set_width(ui_iconBT6, 20);
    lv_obj_set_height(ui_iconBT6, 20);
    lv_obj_set_x(ui_iconBT6, 82);
    lv_obj_set_y(ui_iconBT6, 0);
    lv_obj_set_align(ui_iconBT6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT6, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry6 = lv_label_create(ui_statusBar6);
    lv_obj_set_width(ui_PercentBaterry6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry6, 281);
    lv_obj_set_y(ui_PercentBaterry6, 6);
    lv_label_set_text(ui_PercentBaterry6, "100%");

    ui_Clock6 = lv_label_create(ui_statusBar6);
    lv_obj_set_width(ui_Clock6, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock6, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock6, 1);
    lv_obj_set_y(ui_Clock6, 6);
    lv_obj_set_flex_flow(ui_Clock6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock6, "12:59");
    lv_obj_remove_flag(ui_Clock6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Clock6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY6 = lv_image_create(ui_statusBar6);
    lv_obj_set_width(ui_iconBATERRY6, 20);
    lv_obj_set_height(ui_iconBATERRY6, 20);
    lv_obj_set_x(ui_iconBATERRY6, 106);
    lv_obj_set_y(ui_iconBATERRY6, 0);
    lv_obj_set_align(ui_iconBATERRY6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY6, LV_IMAGE_ALIGN_TILE);

    ui_Container7 = lv_obj_create(ui_ABOUT);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 318);
    lv_obj_set_height(ui_Container7, 444);
    lv_obj_set_x(ui_Container7, 1);
    lv_obj_set_y(ui_Container7, 16);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_button_create(ui_Container7);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 5);
    lv_obj_set_y(ui_Button6, -5);
    lv_obj_set_align(ui_Button6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_state(ui_Button6, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label8 = lv_label_create(ui_ABOUT);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, -47);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Screen 7");

    ui_Bar1 = lv_bar_create(ui_ABOUT);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 298);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 128);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bar1, ui_event_Bar1, LV_EVENT_ALL, NULL);

}

void ui_ABOUT_screen_destroy(void)
{
    if(ui_ABOUT) lv_obj_del(ui_ABOUT);

    // NULL screen variables
    ui_ABOUT = NULL;
    ui_statusBar6 = NULL;
    ui_IconBuzzer6 = NULL;
    ui_iconRS6 = NULL;
    ui_iconNTP6 = NULL;
    ui_iconWIFI6 = NULL;
    ui_iconBT6 = NULL;
    ui_PercentBaterry6 = NULL;
    ui_Clock6 = NULL;
    ui_iconBATERRY6 = NULL;
    ui_Container7 = NULL;
    ui_Button6 = NULL;
    ui_Label8 = NULL;
    ui_Bar1 = NULL;

}
