// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_ABOUT_H
#define UI_ABOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ABOUT
extern void ui_ABOUT_screen_init(void);
extern void ui_ABOUT_screen_destroy(void);
extern lv_obj_t * ui_ABOUT;
extern lv_obj_t * ui_statusBar6;
extern lv_obj_t * ui_IconBuzzer6;
extern lv_obj_t * ui_iconRS6;
extern lv_obj_t * ui_iconNTP6;
extern lv_obj_t * ui_iconWIFI6;
extern lv_obj_t * ui_iconBT6;
extern lv_obj_t * ui_PercentBaterry6;
extern lv_obj_t * ui_Clock6;
extern lv_obj_t * ui_iconBATERRY6;
extern lv_obj_t * ui_Container7;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label8;
extern void ui_event_Bar1(lv_event_t * e);
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

