// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_CC1101 = NULL;
lv_obj_t * ui_statusBar1 = NULL;
lv_obj_t * ui_IconBuzzer1 = NULL;
lv_obj_t * ui_iconRS1 = NULL;
lv_obj_t * ui_iconNTP1 = NULL;
lv_obj_t * ui_iconWIFI1 = NULL;
lv_obj_t * ui_iconBT1 = NULL;
lv_obj_t * ui_PercentBaterry1 = NULL;
lv_obj_t * ui_Clock1 = NULL;
lv_obj_t * ui_iconBATERRY1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuMain, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 150, 0, &ui_MenuMain_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Apply_Settings_CC1101(e);
    }
}

// build funtions

void ui_CC1101_screen_init(void)
{
    ui_CC1101 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CC1101, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusBar1 = lv_obj_create(ui_CC1101);
    lv_obj_remove_style_all(ui_statusBar1);
    lv_obj_set_width(ui_statusBar1, 320);
    lv_obj_set_height(ui_statusBar1, 30);
    lv_obj_set_align(ui_statusBar1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer1 = lv_image_create(ui_statusBar1);
    lv_obj_set_width(ui_IconBuzzer1, 20);
    lv_obj_set_height(ui_IconBuzzer1, 20);
    lv_obj_set_x(ui_IconBuzzer1, 136);
    lv_obj_set_y(ui_IconBuzzer1, 5);
    lv_obj_add_flag(ui_IconBuzzer1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer1, LV_IMAGE_ALIGN_TILE);

    ui_iconRS1 = lv_image_create(ui_statusBar1);
    lv_obj_set_width(ui_iconRS1, 20);
    lv_obj_set_height(ui_iconRS1, 20);
    lv_obj_set_x(ui_iconRS1, 10);
    lv_obj_set_y(ui_iconRS1, 0);
    lv_obj_set_align(ui_iconRS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS1, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP1 = lv_image_create(ui_statusBar1);
    lv_obj_set_width(ui_iconNTP1, 20);
    lv_obj_set_height(ui_iconNTP1, 20);
    lv_obj_set_x(ui_iconNTP1, 34);
    lv_obj_set_y(ui_iconNTP1, 0);
    lv_obj_set_align(ui_iconNTP1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP1, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI1 = lv_image_create(ui_statusBar1);
    lv_obj_set_width(ui_iconWIFI1, 20);
    lv_obj_set_height(ui_iconWIFI1, 20);
    lv_obj_set_x(ui_iconWIFI1, 58);
    lv_obj_set_y(ui_iconWIFI1, 0);
    lv_obj_set_align(ui_iconWIFI1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI1, LV_IMAGE_ALIGN_TILE);

    ui_iconBT1 = lv_image_create(ui_statusBar1);
    lv_obj_set_width(ui_iconBT1, 20);
    lv_obj_set_height(ui_iconBT1, 20);
    lv_obj_set_x(ui_iconBT1, 82);
    lv_obj_set_y(ui_iconBT1, 0);
    lv_obj_set_align(ui_iconBT1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT1, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry1 = lv_label_create(ui_statusBar1);
    lv_obj_set_width(ui_PercentBaterry1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry1, 281);
    lv_obj_set_y(ui_PercentBaterry1, 6);
    lv_label_set_text(ui_PercentBaterry1, "100%");

    ui_Clock1 = lv_label_create(ui_statusBar1);
    lv_obj_set_width(ui_Clock1, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock1, 1);
    lv_obj_set_y(ui_Clock1, 6);
    lv_obj_set_flex_flow(ui_Clock1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock1, "12:59");
    lv_obj_remove_flag(ui_Clock1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Clock1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY1 = lv_image_create(ui_statusBar1);
    lv_obj_set_width(ui_iconBATERRY1, 20);
    lv_obj_set_height(ui_iconBATERRY1, 20);
    lv_obj_set_x(ui_iconBATERRY1, 106);
    lv_obj_set_y(ui_iconBATERRY1, 0);
    lv_obj_set_align(ui_iconBATERRY1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY1, LV_IMAGE_ALIGN_TILE);

    ui_Container1 = lv_obj_create(ui_CC1101);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 318);
    lv_obj_set_height(ui_Container1, 444);
    lv_obj_set_x(ui_Container1, 1);
    lv_obj_set_y(ui_Container1, 16);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 5);
    lv_obj_set_y(ui_Button1, -5);
    lv_obj_set_align(ui_Button1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_state(ui_Button1, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label3 = lv_label_create(ui_CC1101);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 7);
    lv_obj_set_y(ui_Label3, -63);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Screen 3");

    ui_Keyboard1 = lv_keyboard_create(ui_CC1101);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 186);
    lv_obj_set_x(ui_Keyboard1, 1);
    lv_obj_set_y(ui_Keyboard1, -63);

    ui_Label1 = lv_label_create(ui_CC1101);
    lv_obj_set_width(ui_Label1, 83);
    lv_obj_set_height(ui_Label1, 18);
    lv_obj_set_x(ui_Label1, 8);
    lv_obj_set_y(ui_Label1, 41);
    lv_label_set_text(ui_Label1, "Freq MHz:");

    ui_Label5 = lv_label_create(ui_CC1101);
    lv_obj_set_width(ui_Label5, 83);
    lv_obj_set_height(ui_Label5, 18);
    lv_obj_set_x(ui_Label5, 8);
    lv_obj_set_y(ui_Label5, 62);
    lv_label_set_text(ui_Label5, "BitRate:");

    ui_Label9 = lv_label_create(ui_CC1101);
    lv_obj_set_width(ui_Label9, 83);
    lv_obj_set_height(ui_Label9, 18);
    lv_obj_set_x(ui_Label9, 7);
    lv_obj_set_y(ui_Label9, 85);
    lv_label_set_text(ui_Label9, "RxBw:");

    ui_Label10 = lv_label_create(ui_CC1101);
    lv_obj_set_width(ui_Label10, 83);
    lv_obj_set_height(ui_Label10, 18);
    lv_obj_set_x(ui_Label10, 6);
    lv_obj_set_y(ui_Label10, 108);
    lv_label_set_text(ui_Label10, "Mod:");

    ui_Label11 = lv_label_create(ui_CC1101);
    lv_obj_set_width(ui_Label11, 83);
    lv_obj_set_height(ui_Label11, 18);
    lv_obj_set_x(ui_Label11, 7);
    lv_obj_set_y(ui_Label11, 132);
    lv_label_set_text(ui_Label11, "Power:");

    ui_Button7 = lv_button_create(ui_CC1101);
    lv_obj_set_width(ui_Button7, 59);
    lv_obj_set_height(ui_Button7, 24);
    lv_obj_set_x(ui_Button7, 6);
    lv_obj_set_y(ui_Button7, 153);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_CC1101);
    lv_obj_set_width(ui_TextArea1, 112);
    lv_obj_set_height(ui_TextArea1, 33);
    lv_obj_set_x(ui_TextArea1, 95);
    lv_obj_set_y(ui_TextArea1, 30);
    lv_textarea_set_text(ui_TextArea1, "433.96");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}

void ui_CC1101_screen_destroy(void)
{
    if(ui_CC1101) lv_obj_del(ui_CC1101);

    // NULL screen variables
    ui_CC1101 = NULL;
    ui_statusBar1 = NULL;
    ui_IconBuzzer1 = NULL;
    ui_iconRS1 = NULL;
    ui_iconNTP1 = NULL;
    ui_iconWIFI1 = NULL;
    ui_iconBT1 = NULL;
    ui_PercentBaterry1 = NULL;
    ui_Clock1 = NULL;
    ui_iconBATERRY1 = NULL;
    ui_Container1 = NULL;
    ui_Button1 = NULL;
    ui_Label3 = NULL;
    ui_Keyboard1 = NULL;
    ui_Label1 = NULL;
    ui_Label5 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Button7 = NULL;
    ui_TextArea1 = NULL;

}
