// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_CC1101_H
#define UI_CC1101_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CC1101
extern void ui_CC1101_screen_init(void);
extern void ui_CC1101_screen_destroy(void);
extern lv_obj_t * ui_CC1101;
extern lv_obj_t * ui_statusBar1;
extern lv_obj_t * ui_IconBuzzer1;
extern lv_obj_t * ui_iconRS1;
extern lv_obj_t * ui_iconNTP1;
extern lv_obj_t * ui_iconWIFI1;
extern lv_obj_t * ui_iconBT1;
extern lv_obj_t * ui_PercentBaterry1;
extern lv_obj_t * ui_Clock1;
extern lv_obj_t * ui_iconBATERRY1;
extern lv_obj_t * ui_Container1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

