// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_LORA = NULL;
lv_obj_t * ui_statusBar4 = NULL;
lv_obj_t * ui_IconBuzzer4 = NULL;
lv_obj_t * ui_iconRS4 = NULL;
lv_obj_t * ui_iconNTP4 = NULL;
lv_obj_t * ui_iconWIFI4 = NULL;
lv_obj_t * ui_iconBT4 = NULL;
lv_obj_t * ui_PercentBaterry4 = NULL;
lv_obj_t * ui_Clock4 = NULL;
lv_obj_t * ui_iconBATERRY4 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuMain, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuMain_screen_init);
    }
}

// build funtions

void ui_LORA_screen_init(void)
{
    ui_LORA = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LORA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusBar4 = lv_obj_create(ui_LORA);
    lv_obj_remove_style_all(ui_statusBar4);
    lv_obj_set_width(ui_statusBar4, 320);
    lv_obj_set_height(ui_statusBar4, 30);
    lv_obj_set_align(ui_statusBar4, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer4 = lv_image_create(ui_statusBar4);
    lv_obj_set_width(ui_IconBuzzer4, 20);
    lv_obj_set_height(ui_IconBuzzer4, 20);
    lv_obj_set_x(ui_IconBuzzer4, 136);
    lv_obj_set_y(ui_IconBuzzer4, 5);
    lv_obj_add_flag(ui_IconBuzzer4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer4, LV_IMAGE_ALIGN_TILE);

    ui_iconRS4 = lv_image_create(ui_statusBar4);
    lv_obj_set_width(ui_iconRS4, 20);
    lv_obj_set_height(ui_iconRS4, 20);
    lv_obj_set_x(ui_iconRS4, 10);
    lv_obj_set_y(ui_iconRS4, 0);
    lv_obj_set_align(ui_iconRS4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS4, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP4 = lv_image_create(ui_statusBar4);
    lv_obj_set_width(ui_iconNTP4, 20);
    lv_obj_set_height(ui_iconNTP4, 20);
    lv_obj_set_x(ui_iconNTP4, 34);
    lv_obj_set_y(ui_iconNTP4, 0);
    lv_obj_set_align(ui_iconNTP4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP4, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI4 = lv_image_create(ui_statusBar4);
    lv_obj_set_width(ui_iconWIFI4, 20);
    lv_obj_set_height(ui_iconWIFI4, 20);
    lv_obj_set_x(ui_iconWIFI4, 58);
    lv_obj_set_y(ui_iconWIFI4, 0);
    lv_obj_set_align(ui_iconWIFI4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI4, LV_IMAGE_ALIGN_TILE);

    ui_iconBT4 = lv_image_create(ui_statusBar4);
    lv_obj_set_width(ui_iconBT4, 20);
    lv_obj_set_height(ui_iconBT4, 20);
    lv_obj_set_x(ui_iconBT4, 82);
    lv_obj_set_y(ui_iconBT4, 0);
    lv_obj_set_align(ui_iconBT4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT4, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry4 = lv_label_create(ui_statusBar4);
    lv_obj_set_width(ui_PercentBaterry4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry4, 281);
    lv_obj_set_y(ui_PercentBaterry4, 6);
    lv_label_set_text(ui_PercentBaterry4, "100%");

    ui_Clock4 = lv_label_create(ui_statusBar4);
    lv_obj_set_width(ui_Clock4, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock4, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock4, 1);
    lv_obj_set_y(ui_Clock4, 6);
    lv_obj_set_flex_flow(ui_Clock4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock4, "12:59");
    lv_obj_remove_flag(ui_Clock4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Clock4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY4 = lv_image_create(ui_statusBar4);
    lv_obj_set_width(ui_iconBATERRY4, 20);
    lv_obj_set_height(ui_iconBATERRY4, 20);
    lv_obj_set_x(ui_iconBATERRY4, 106);
    lv_obj_set_y(ui_iconBATERRY4, 0);
    lv_obj_set_align(ui_iconBATERRY4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY4, LV_IMAGE_ALIGN_TILE);

    ui_Container5 = lv_obj_create(ui_LORA);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 318);
    lv_obj_set_height(ui_Container5, 444);
    lv_obj_set_x(ui_Container5, 1);
    lv_obj_set_y(ui_Container5, 16);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 5);
    lv_obj_set_y(ui_Button4, -5);
    lv_obj_set_align(ui_Button4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_state(ui_Button4, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label6 = lv_label_create(ui_LORA);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 11);
    lv_obj_set_y(ui_Label6, -51);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Screen 5");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_LORA_screen_destroy(void)
{
    if(ui_LORA) lv_obj_del(ui_LORA);

    // NULL screen variables
    ui_LORA = NULL;
    ui_statusBar4 = NULL;
    ui_IconBuzzer4 = NULL;
    ui_iconRS4 = NULL;
    ui_iconNTP4 = NULL;
    ui_iconWIFI4 = NULL;
    ui_iconBT4 = NULL;
    ui_PercentBaterry4 = NULL;
    ui_Clock4 = NULL;
    ui_iconBATERRY4 = NULL;
    ui_Container5 = NULL;
    ui_Button4 = NULL;
    ui_Label6 = NULL;

}
