// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_LORA_H
#define UI_LORA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LORA
extern void ui_LORA_screen_init(void);
extern void ui_LORA_screen_destroy(void);
extern lv_obj_t * ui_LORA;
extern lv_obj_t * ui_statusBar4;
extern lv_obj_t * ui_IconBuzzer4;
extern lv_obj_t * ui_iconRS4;
extern lv_obj_t * ui_iconNTP4;
extern lv_obj_t * ui_iconWIFI4;
extern lv_obj_t * ui_iconBT4;
extern lv_obj_t * ui_PercentBaterry4;
extern lv_obj_t * ui_Clock4;
extern lv_obj_t * ui_iconBATERRY4;
extern lv_obj_t * ui_Container5;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

