// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_MENUMAIN_H
#define UI_MENUMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuMain
extern void ui_MenuMain_screen_init(void);
extern void ui_MenuMain_screen_destroy(void);
extern lv_obj_t * ui_MenuMain;
extern lv_obj_t * ui_statusBar;
extern lv_obj_t * ui_IconBuzzer;
extern lv_obj_t * ui_iconRS485;
extern lv_obj_t * ui_iconNTP;
extern lv_obj_t * ui_iconWIFI;
extern lv_obj_t * ui_iconBT;
extern lv_obj_t * ui_PercentBaterry;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_iconBATERRY;
extern lv_obj_t * ui_Container2;
extern void ui_event_ImgBtnMenuMain(lv_event_t * e);
extern lv_obj_t * ui_ImgBtnMenuMain;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_statusBar;
extern lv_obj_t * uic_Clock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

