// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * uic_Clock;
lv_obj_t * uic_statusBar;
lv_obj_t * ui_MenuMain = NULL;
lv_obj_t * ui_statusBar = NULL;
lv_obj_t * ui_IconBuzzer = NULL;
lv_obj_t * ui_iconRS485 = NULL;
lv_obj_t * ui_iconNTP = NULL;
lv_obj_t * ui_iconWIFI = NULL;
lv_obj_t * ui_iconBT = NULL;
lv_obj_t * ui_PercentBaterry = NULL;
lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_iconBATERRY = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ImgBtnMenuMain = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
// event funtions
void ui_event_ImgBtnMenuMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCREEN_LOAD_ANIM_FADE_ON, 150, 0, &ui_Settings_screen_init);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CC1101, LV_SCREEN_LOAD_ANIM_FADE_ON, 150, 0, &ui_CC1101_screen_init);
    }
}

void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NRF24L01, LV_SCREEN_LOAD_ANIM_FADE_ON, 150, 0, &ui_NRF24L01_screen_init);
    }
}

void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LORA, LV_SCREEN_LOAD_ANIM_FADE_ON, 150, 0, &ui_LORA_screen_init);
    }
}

void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RSSIPLOTTER, LV_SCREEN_LOAD_ANIM_FADE_ON, 150, 0, &ui_RSSIPLOTTER_screen_init);
    }
}

void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ABOUT, LV_SCREEN_LOAD_ANIM_FADE_ON, 150, 0, &ui_ABOUT_screen_init);
    }
}

// build funtions

void ui_MenuMain_screen_init(void)
{
    ui_MenuMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_MenuMain, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_MenuMain_screen_destroy);

    ui_statusBar = lv_obj_create(ui_MenuMain);
    lv_obj_remove_style_all(ui_statusBar);
    lv_obj_set_width(ui_statusBar, 320);
    lv_obj_set_height(ui_statusBar, 30);
    lv_obj_set_align(ui_statusBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer = lv_image_create(ui_statusBar);
    lv_obj_set_width(ui_IconBuzzer, 20);
    lv_obj_set_height(ui_IconBuzzer, 20);
    lv_obj_set_x(ui_IconBuzzer, 136);
    lv_obj_set_y(ui_IconBuzzer, 5);
    lv_obj_add_flag(ui_IconBuzzer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_image_recolor(ui_IconBuzzer, lv_color_hex(0x1CC108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IconBuzzer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconRS485 = lv_image_create(ui_statusBar);
    lv_obj_set_width(ui_iconRS485, 20);
    lv_obj_set_height(ui_iconRS485, 20);
    lv_obj_set_x(ui_iconRS485, 10);
    lv_obj_set_y(ui_iconRS485, 0);
    lv_obj_set_align(ui_iconRS485, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS485, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS485, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS485, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP = lv_image_create(ui_statusBar);
    lv_obj_set_width(ui_iconNTP, 20);
    lv_obj_set_height(ui_iconNTP, 20);
    lv_obj_set_x(ui_iconNTP, 34);
    lv_obj_set_y(ui_iconNTP, 0);
    lv_obj_set_align(ui_iconNTP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI = lv_image_create(ui_statusBar);
    lv_obj_set_width(ui_iconWIFI, 20);
    lv_obj_set_height(ui_iconWIFI, 20);
    lv_obj_set_x(ui_iconWIFI, 58);
    lv_obj_set_y(ui_iconWIFI, 0);
    lv_obj_set_align(ui_iconWIFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI, LV_IMAGE_ALIGN_TILE);

    ui_iconBT = lv_image_create(ui_statusBar);
    lv_obj_set_width(ui_iconBT, 20);
    lv_obj_set_height(ui_iconBT, 20);
    lv_obj_set_x(ui_iconBT, 82);
    lv_obj_set_y(ui_iconBT, 0);
    lv_obj_set_align(ui_iconBT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry = lv_label_create(ui_statusBar);
    lv_obj_set_width(ui_PercentBaterry, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry, 281);
    lv_obj_set_y(ui_PercentBaterry, 6);
    lv_label_set_text(ui_PercentBaterry, "100%");

    ui_Clock = lv_label_create(ui_statusBar);
    lv_obj_set_width(ui_Clock, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock, 1);
    lv_obj_set_y(ui_Clock, 6);
    lv_obj_set_flex_flow(ui_Clock, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock, "12:59");
    lv_label_set_recolor(ui_Clock, true);
    lv_obj_remove_flag(ui_Clock, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Clock, lv_color_hex(0x0FBF26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY = lv_image_create(ui_statusBar);
    lv_obj_set_width(ui_iconBATERRY, 20);
    lv_obj_set_height(ui_iconBATERRY, 20);
    lv_obj_set_x(ui_iconBATERRY, 106);
    lv_obj_set_y(ui_iconBATERRY, 0);
    lv_obj_set_align(ui_iconBATERRY, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY, LV_IMAGE_ALIGN_TILE);

    ui_Container2 = lv_obj_create(ui_MenuMain);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, 450);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 30);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBtnMenuMain = lv_btn_create(ui_Container2);
    lv_obj_set_size(ui_ImgBtnMenuMain, 64, 64);
    lv_obj_set_x(ui_ImgBtnMenuMain, 60);
    lv_obj_set_y(ui_ImgBtnMenuMain, 60);
    lv_obj_add_flag(ui_ImgBtnMenuMain, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_ImgBtnMenuMain, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgBtnMenuMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t * label = lv_label_create(ui_ImgBtnMenuMain);
        lv_label_set_text(label, "Settings");
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);
    }

    ui_ImgButton2 = lv_btn_create(ui_Container2);
    lv_obj_set_size(ui_ImgButton2, 64, 64);
    lv_obj_set_x(ui_ImgButton2, 196);
    lv_obj_set_y(ui_ImgButton2, 60);
    lv_obj_add_flag(ui_ImgButton2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_ImgButton2, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t * label = lv_label_create(ui_ImgButton2);
        lv_label_set_text(label, "CC1101");
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);
    }

    ui_ImgButton3 = lv_btn_create(ui_Container2);
    lv_obj_set_size(ui_ImgButton3, 64, 64);
    lv_obj_set_x(ui_ImgButton3, 60);
    lv_obj_set_y(ui_ImgButton3, 190);
    lv_obj_add_flag(ui_ImgButton3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_ImgButton3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t * label = lv_label_create(ui_ImgButton3);
        lv_label_set_text(label, "NRF24");
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);
    }

    ui_ImgButton4 = lv_btn_create(ui_Container2);
    lv_obj_set_size(ui_ImgButton4, 64, 64);
    lv_obj_set_x(ui_ImgButton4, 196);
    lv_obj_set_y(ui_ImgButton4, 190);
    lv_obj_add_flag(ui_ImgButton4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_ImgButton4, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t * label = lv_label_create(ui_ImgButton4);
        lv_label_set_text(label, "LoRa");
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);
    }

    ui_ImgButton5 = lv_btn_create(ui_Container2);
    lv_obj_set_size(ui_ImgButton5, 64, 64);
    lv_obj_set_x(ui_ImgButton5, 60);
    lv_obj_set_y(ui_ImgButton5, 320);
    lv_obj_add_flag(ui_ImgButton5, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_ImgButton5, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t * label = lv_label_create(ui_ImgButton5);
        lv_label_set_text(label, "RSSI");
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);
    }

    ui_ImgButton6 = lv_btn_create(ui_Container2);
    lv_obj_set_size(ui_ImgButton6, 64, 64);
    lv_obj_set_x(ui_ImgButton6, 196);
    lv_obj_set_y(ui_ImgButton6, 320);
    lv_obj_add_flag(ui_ImgButton6, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_ImgButton6, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t * label = lv_label_create(ui_ImgButton6);
        lv_label_set_text(label, "About");
        lv_obj_set_align(label, LV_ALIGN_CENTER);
        lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);
    }

    lv_obj_add_event_cb(ui_ImgBtnMenuMain, ui_event_ImgBtnMenuMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    uic_statusBar = ui_statusBar;
    uic_Clock = ui_Clock;

}

void ui_MenuMain_screen_destroy(void)
{
    if(ui_MenuMain) lv_obj_del(ui_MenuMain);

    // NULL screen variables
    ui_MenuMain = NULL;
    uic_statusBar = NULL;
    ui_statusBar = NULL;
    ui_IconBuzzer = NULL;
    ui_iconRS485 = NULL;
    ui_iconNTP = NULL;
    ui_iconWIFI = NULL;
    ui_iconBT = NULL;
    ui_PercentBaterry = NULL;
    uic_Clock = NULL;
    ui_Clock = NULL;
    ui_iconBATERRY = NULL;
    ui_Container2 = NULL;
    ui_ImgBtnMenuMain = NULL;
    ui_ImgButton2 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton4 = NULL;
    ui_ImgButton5 = NULL;
    ui_ImgButton6 = NULL;

}
