// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_NRF24L01_H
#define UI_NRF24L01_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NRF24L01
extern void ui_NRF24L01_screen_init(void);
extern void ui_NRF24L01_screen_destroy(void);
extern lv_obj_t * ui_NRF24L01;
extern lv_obj_t * ui_statusBar3;
extern lv_obj_t * ui_IconBuzzer3;
extern lv_obj_t * ui_iconRS3;
extern lv_obj_t * ui_iconNTP3;
extern lv_obj_t * ui_iconWIFI3;
extern lv_obj_t * ui_iconBT3;
extern lv_obj_t * ui_PercentBaterry3;
extern lv_obj_t * ui_Clock3;
extern lv_obj_t * ui_iconBATERRY3;
extern lv_obj_t * ui_Container4;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

