// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_NRF24L01 = NULL;
lv_obj_t * ui_statusBar3 = NULL;
lv_obj_t * ui_IconBuzzer3 = NULL;
lv_obj_t * ui_iconRS3 = NULL;
lv_obj_t * ui_iconNTP3 = NULL;
lv_obj_t * ui_iconWIFI3 = NULL;
lv_obj_t * ui_iconBT3 = NULL;
lv_obj_t * ui_PercentBaterry3 = NULL;
lv_obj_t * ui_Clock3 = NULL;
lv_obj_t * ui_iconBATERRY3 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuMain, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuMain_screen_init);
    }
}

// build funtions

void ui_NRF24L01_screen_init(void)
{
    ui_NRF24L01 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NRF24L01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusBar3 = lv_obj_create(ui_NRF24L01);
    lv_obj_remove_style_all(ui_statusBar3);
    lv_obj_set_width(ui_statusBar3, 320);
    lv_obj_set_height(ui_statusBar3, 30);
    lv_obj_set_align(ui_statusBar3, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer3 = lv_image_create(ui_statusBar3);
    lv_obj_set_width(ui_IconBuzzer3, 20);
    lv_obj_set_height(ui_IconBuzzer3, 20);
    lv_obj_set_x(ui_IconBuzzer3, 136);
    lv_obj_set_y(ui_IconBuzzer3, 5);
    lv_obj_add_flag(ui_IconBuzzer3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer3, LV_IMAGE_ALIGN_TILE);

    ui_iconRS3 = lv_image_create(ui_statusBar3);
    lv_obj_set_width(ui_iconRS3, 20);
    lv_obj_set_height(ui_iconRS3, 20);
    lv_obj_set_x(ui_iconRS3, 10);
    lv_obj_set_y(ui_iconRS3, 0);
    lv_obj_set_align(ui_iconRS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS3, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP3 = lv_image_create(ui_statusBar3);
    lv_obj_set_width(ui_iconNTP3, 20);
    lv_obj_set_height(ui_iconNTP3, 20);
    lv_obj_set_x(ui_iconNTP3, 34);
    lv_obj_set_y(ui_iconNTP3, 0);
    lv_obj_set_align(ui_iconNTP3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP3, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI3 = lv_image_create(ui_statusBar3);
    lv_obj_set_width(ui_iconWIFI3, 20);
    lv_obj_set_height(ui_iconWIFI3, 20);
    lv_obj_set_x(ui_iconWIFI3, 58);
    lv_obj_set_y(ui_iconWIFI3, 0);
    lv_obj_set_align(ui_iconWIFI3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI3, LV_IMAGE_ALIGN_TILE);

    ui_iconBT3 = lv_image_create(ui_statusBar3);
    lv_obj_set_width(ui_iconBT3, 20);
    lv_obj_set_height(ui_iconBT3, 20);
    lv_obj_set_x(ui_iconBT3, 82);
    lv_obj_set_y(ui_iconBT3, 0);
    lv_obj_set_align(ui_iconBT3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT3, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry3 = lv_label_create(ui_statusBar3);
    lv_obj_set_width(ui_PercentBaterry3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry3, 281);
    lv_obj_set_y(ui_PercentBaterry3, 6);
    lv_label_set_text(ui_PercentBaterry3, "100%");

    ui_Clock3 = lv_label_create(ui_statusBar3);
    lv_obj_set_width(ui_Clock3, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock3, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock3, 1);
    lv_obj_set_y(ui_Clock3, 6);
    lv_obj_set_flex_flow(ui_Clock3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock3, "12:59");
    lv_obj_remove_flag(ui_Clock3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Clock3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY3 = lv_image_create(ui_statusBar3);
    lv_obj_set_width(ui_iconBATERRY3, 20);
    lv_obj_set_height(ui_iconBATERRY3, 20);
    lv_obj_set_x(ui_iconBATERRY3, 106);
    lv_obj_set_y(ui_iconBATERRY3, 0);
    lv_obj_set_align(ui_iconBATERRY3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY3, LV_IMAGE_ALIGN_TILE);

    ui_Container4 = lv_obj_create(ui_NRF24L01);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 318);
    lv_obj_set_height(ui_Container4, 444);
    lv_obj_set_x(ui_Container4, 1);
    lv_obj_set_y(ui_Container4, 16);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Container4);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 5);
    lv_obj_set_y(ui_Button2, -5);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Button2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_Button2, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label4 = lv_label_create(ui_NRF24L01);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -13);
    lv_obj_set_y(ui_Label4, -55);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Screen 4");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_NRF24L01_screen_destroy(void)
{
    if(ui_NRF24L01) lv_obj_del(ui_NRF24L01);

    // NULL screen variables
    ui_NRF24L01 = NULL;
    ui_statusBar3 = NULL;
    ui_IconBuzzer3 = NULL;
    ui_iconRS3 = NULL;
    ui_iconNTP3 = NULL;
    ui_iconWIFI3 = NULL;
    ui_iconBT3 = NULL;
    ui_PercentBaterry3 = NULL;
    ui_Clock3 = NULL;
    ui_iconBATERRY3 = NULL;
    ui_Container4 = NULL;
    ui_Button2 = NULL;
    ui_Label4 = NULL;

}
