// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_RSSIPLOTTER = NULL;
lv_obj_t * ui_statusBar5 = NULL;
lv_obj_t * ui_IconBuzzer5 = NULL;
lv_obj_t * ui_iconRS5 = NULL;
lv_obj_t * ui_iconNTP5 = NULL;
lv_obj_t * ui_iconWIFI5 = NULL;
lv_obj_t * ui_iconBT5 = NULL;
lv_obj_t * ui_PercentBaterry5 = NULL;
lv_obj_t * ui_Clock5 = NULL;
lv_obj_t * ui_iconBATERRY5 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
// event funtions
void ui_event_RSSIPLOTTER(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen8_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuMain, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuMain_screen_init);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen8_screen_init);
    }
}

// build funtions

void ui_RSSIPLOTTER_screen_init(void)
{
    ui_RSSIPLOTTER = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RSSIPLOTTER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusBar5 = lv_obj_create(ui_RSSIPLOTTER);
    lv_obj_remove_style_all(ui_statusBar5);
    lv_obj_set_width(ui_statusBar5, 320);
    lv_obj_set_height(ui_statusBar5, 30);
    lv_obj_set_align(ui_statusBar5, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer5 = lv_image_create(ui_statusBar5);
    lv_obj_set_width(ui_IconBuzzer5, 20);
    lv_obj_set_height(ui_IconBuzzer5, 20);
    lv_obj_set_x(ui_IconBuzzer5, 136);
    lv_obj_set_y(ui_IconBuzzer5, 5);
    lv_obj_add_flag(ui_IconBuzzer5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer5, LV_IMAGE_ALIGN_TILE);

    ui_iconRS5 = lv_image_create(ui_statusBar5);
    lv_obj_set_width(ui_iconRS5, 20);
    lv_obj_set_height(ui_iconRS5, 20);
    lv_obj_set_x(ui_iconRS5, 10);
    lv_obj_set_y(ui_iconRS5, 0);
    lv_obj_set_align(ui_iconRS5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS5, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP5 = lv_image_create(ui_statusBar5);
    lv_obj_set_width(ui_iconNTP5, 20);
    lv_obj_set_height(ui_iconNTP5, 20);
    lv_obj_set_x(ui_iconNTP5, 34);
    lv_obj_set_y(ui_iconNTP5, 0);
    lv_obj_set_align(ui_iconNTP5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP5, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI5 = lv_image_create(ui_statusBar5);
    lv_obj_set_width(ui_iconWIFI5, 20);
    lv_obj_set_height(ui_iconWIFI5, 20);
    lv_obj_set_x(ui_iconWIFI5, 58);
    lv_obj_set_y(ui_iconWIFI5, 0);
    lv_obj_set_align(ui_iconWIFI5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI5, LV_IMAGE_ALIGN_TILE);

    ui_iconBT5 = lv_image_create(ui_statusBar5);
    lv_obj_set_width(ui_iconBT5, 20);
    lv_obj_set_height(ui_iconBT5, 20);
    lv_obj_set_x(ui_iconBT5, 82);
    lv_obj_set_y(ui_iconBT5, 0);
    lv_obj_set_align(ui_iconBT5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT5, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry5 = lv_label_create(ui_statusBar5);
    lv_obj_set_width(ui_PercentBaterry5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry5, 281);
    lv_obj_set_y(ui_PercentBaterry5, 6);
    lv_label_set_text(ui_PercentBaterry5, "100%");

    ui_Clock5 = lv_label_create(ui_statusBar5);
    lv_obj_set_width(ui_Clock5, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock5, 1);
    lv_obj_set_y(ui_Clock5, 6);
    lv_obj_set_flex_flow(ui_Clock5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock5, "12:59");
    lv_obj_remove_flag(ui_Clock5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Clock5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY5 = lv_image_create(ui_statusBar5);
    lv_obj_set_width(ui_iconBATERRY5, 20);
    lv_obj_set_height(ui_iconBATERRY5, 20);
    lv_obj_set_x(ui_iconBATERRY5, 106);
    lv_obj_set_y(ui_iconBATERRY5, 0);
    lv_obj_set_align(ui_iconBATERRY5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY5, LV_IMAGE_ALIGN_TILE);

    ui_Container6 = lv_obj_create(ui_RSSIPLOTTER);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 318);
    lv_obj_set_height(ui_Container6, 444);
    lv_obj_set_x(ui_Container6, 1);
    lv_obj_set_y(ui_Container6, 16);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 5);
    lv_obj_set_y(ui_Button5, -5);
    lv_obj_set_align(ui_Button5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_state(ui_Button5, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label7 = lv_label_create(ui_RSSIPLOTTER);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -9);
    lv_obj_set_y(ui_Label7, -51);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Screen 6");

    ui_ImgButton1 = lv_imagebutton_create(ui_RSSIPLOTTER);
    lv_obj_set_width(ui_ImgButton1, 64);
    lv_obj_set_height(ui_ImgButton1, 64);
    lv_obj_set_x(ui_ImgButton1, -24);
    lv_obj_set_y(ui_ImgButton1, -105);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RSSIPLOTTER, ui_event_RSSIPLOTTER, LV_EVENT_ALL, NULL);

}

void ui_RSSIPLOTTER_screen_destroy(void)
{
    if(ui_RSSIPLOTTER) lv_obj_del(ui_RSSIPLOTTER);

    // NULL screen variables
    ui_RSSIPLOTTER = NULL;
    ui_statusBar5 = NULL;
    ui_IconBuzzer5 = NULL;
    ui_iconRS5 = NULL;
    ui_iconNTP5 = NULL;
    ui_iconWIFI5 = NULL;
    ui_iconBT5 = NULL;
    ui_PercentBaterry5 = NULL;
    ui_Clock5 = NULL;
    ui_iconBATERRY5 = NULL;
    ui_Container6 = NULL;
    ui_Button5 = NULL;
    ui_Label7 = NULL;
    ui_ImgButton1 = NULL;

}
