// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_RSSIPLOTTER_H
#define UI_RSSIPLOTTER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RSSIPLOTTER
extern void ui_RSSIPLOTTER_screen_init(void);
extern void ui_RSSIPLOTTER_screen_destroy(void);
extern void ui_event_RSSIPLOTTER(lv_event_t * e);
extern lv_obj_t * ui_RSSIPLOTTER;
extern lv_obj_t * ui_statusBar5;
extern lv_obj_t * ui_IconBuzzer5;
extern lv_obj_t * ui_iconRS5;
extern lv_obj_t * ui_iconNTP5;
extern lv_obj_t * ui_iconWIFI5;
extern lv_obj_t * ui_iconBT5;
extern lv_obj_t * ui_PercentBaterry5;
extern lv_obj_t * ui_Clock5;
extern lv_obj_t * ui_iconBATERRY5;
extern lv_obj_t * ui_Container6;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label7;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

