// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_statusBar2 = NULL;
lv_obj_t * ui_IconBuzzer2 = NULL;
lv_obj_t * ui_iconRS2 = NULL;
lv_obj_t * ui_iconNTP2 = NULL;
lv_obj_t * ui_iconWIFI2 = NULL;
lv_obj_t * ui_iconBT2 = NULL;
lv_obj_t * ui_PercentBaterry2 = NULL;
lv_obj_t * ui_Clock2 = NULL;
lv_obj_t * ui_iconBATERRY2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuMain, LV_SCREEN_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_MenuMain_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statusBar2 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_statusBar2);
    lv_obj_set_width(ui_statusBar2, 320);
    lv_obj_set_height(ui_statusBar2, 30);
    lv_obj_set_align(ui_statusBar2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statusBar2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusBar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconBuzzer2 = lv_image_create(ui_statusBar2);
    lv_obj_set_width(ui_IconBuzzer2, 20);
    lv_obj_set_height(ui_IconBuzzer2, 20);
    lv_obj_set_x(ui_IconBuzzer2, 136);
    lv_obj_set_y(ui_IconBuzzer2, 5);
    lv_obj_add_flag(ui_IconBuzzer2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_IconBuzzer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_IconBuzzer2, LV_IMAGE_ALIGN_TILE);

    ui_iconRS2 = lv_image_create(ui_statusBar2);
    lv_obj_set_width(ui_iconRS2, 20);
    lv_obj_set_height(ui_iconRS2, 20);
    lv_obj_set_x(ui_iconRS2, 10);
    lv_obj_set_y(ui_iconRS2, 0);
    lv_obj_set_align(ui_iconRS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconRS2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconRS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconRS2, LV_IMAGE_ALIGN_TILE);

    ui_iconNTP2 = lv_image_create(ui_statusBar2);
    lv_obj_set_width(ui_iconNTP2, 20);
    lv_obj_set_height(ui_iconNTP2, 20);
    lv_obj_set_x(ui_iconNTP2, 34);
    lv_obj_set_y(ui_iconNTP2, 0);
    lv_obj_set_align(ui_iconNTP2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconNTP2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconNTP2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconNTP2, LV_IMAGE_ALIGN_TILE);

    ui_iconWIFI2 = lv_image_create(ui_statusBar2);
    lv_obj_set_width(ui_iconWIFI2, 20);
    lv_obj_set_height(ui_iconWIFI2, 20);
    lv_obj_set_x(ui_iconWIFI2, 58);
    lv_obj_set_y(ui_iconWIFI2, 0);
    lv_obj_set_align(ui_iconWIFI2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWIFI2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconWIFI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconWIFI2, LV_IMAGE_ALIGN_TILE);

    ui_iconBT2 = lv_image_create(ui_statusBar2);
    lv_obj_set_width(ui_iconBT2, 20);
    lv_obj_set_height(ui_iconBT2, 20);
    lv_obj_set_x(ui_iconBT2, 82);
    lv_obj_set_y(ui_iconBT2, 0);
    lv_obj_set_align(ui_iconBT2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBT2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBT2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBT2, LV_IMAGE_ALIGN_TILE);

    ui_PercentBaterry2 = lv_label_create(ui_statusBar2);
    lv_obj_set_width(ui_PercentBaterry2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBaterry2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBaterry2, 281);
    lv_obj_set_y(ui_PercentBaterry2, 6);
    lv_label_set_text(ui_PercentBaterry2, "100%");

    ui_Clock2 = lv_label_create(ui_statusBar2);
    lv_obj_set_width(ui_Clock2, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Clock2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Clock2, 1);
    lv_obj_set_y(ui_Clock2, 6);
    lv_obj_set_flex_flow(ui_Clock2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Clock2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Clock2, "12:59");
    lv_obj_remove_flag(ui_Clock2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Clock2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clock2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clock2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconBATERRY2 = lv_image_create(ui_statusBar2);
    lv_obj_set_width(ui_iconBATERRY2, 20);
    lv_obj_set_height(ui_iconBATERRY2, 20);
    lv_obj_set_x(ui_iconBATERRY2, 106);
    lv_obj_set_y(ui_iconBATERRY2, 0);
    lv_obj_set_align(ui_iconBATERRY2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconBATERRY2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_iconBATERRY2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_iconBATERRY2, LV_IMAGE_ALIGN_TILE);

    ui_Container3 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 318);
    lv_obj_set_height(ui_Container3, 444);
    lv_obj_set_x(ui_Container3, 1);
    lv_obj_set_y(ui_Container3, 16);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 5);
    lv_obj_set_y(ui_Button3, -5);
    lv_obj_set_align(ui_Button3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_state(ui_Button3, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -8);
    lv_obj_set_y(ui_Label2, -89);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Screen 2");

    ui_Switch1 = lv_switch_create(ui_Settings);
    lv_obj_set_width(ui_Switch1, 73);
    lv_obj_set_height(ui_Switch1, 37);
    lv_obj_set_x(ui_Switch1, 51);
    lv_obj_set_y(ui_Switch1, 82);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Roller1 = lv_roller_create(ui_Settings);
    lv_roller_set_options(ui_Roller1,
                          "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6\nOption 7\nOption 8\nOption 9\nOption 10\nOption 11\nOption 12\nOption 13\nOption 14\n\n\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 381);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 12);
    lv_obj_set_y(ui_Roller1, 37);
    lv_obj_set_flex_flow(ui_Roller1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Roller1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Dropdown1 = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_Dropdown1,
                            "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6\nOption 7\nOption 8\nOption 9\nOption 10\nOption 11\nOption 12\nOption 13\nOption 14\n\n\n");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 143);
    lv_obj_set_y(ui_Dropdown1, 42);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_statusBar2 = NULL;
    ui_IconBuzzer2 = NULL;
    ui_iconRS2 = NULL;
    ui_iconNTP2 = NULL;
    ui_iconWIFI2 = NULL;
    ui_iconBT2 = NULL;
    ui_PercentBaterry2 = NULL;
    ui_Clock2 = NULL;
    ui_iconBATERRY2 = NULL;
    ui_Container3 = NULL;
    ui_Button3 = NULL;
    ui_Label2 = NULL;
    ui_Switch1 = NULL;
    ui_Roller1 = NULL;
    ui_Dropdown1 = NULL;

}
