// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_Screen10 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
// event funtions
void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen9, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen9_screen_init);
    }
}

// build funtions

void ui_Screen10_screen_init(void)
{
    ui_Screen10 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton9 = lv_imagebutton_create(ui_Screen10);
    lv_obj_set_width(ui_ImgButton9, 64);
    lv_obj_set_height(ui_ImgButton9, 64);
    lv_obj_set_x(ui_ImgButton9, -103);
    lv_obj_set_y(ui_ImgButton9, 177);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);

}

void ui_Screen10_screen_destroy(void)
{
    if(ui_Screen10) lv_obj_del(ui_Screen10);

    // NULL screen variables
    ui_Screen10 = NULL;
    ui_ImgButton9 = NULL;

}
