// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#include "../ui.h"

lv_obj_t * ui_Screen9 = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
lv_obj_t * ui_ImgButton10 = NULL;
// event funtions
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen10, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen10_screen_init);
    }
}

void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen8_screen_init);
    }
}

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton8 = lv_imagebutton_create(ui_Screen9);
    lv_obj_set_width(ui_ImgButton8, 64);
    lv_obj_set_height(ui_ImgButton8, 64);
    lv_obj_set_x(ui_ImgButton8, 39);
    lv_obj_set_y(ui_ImgButton8, -61);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    ui_ImgButton10 = lv_imagebutton_create(ui_Screen9);
    lv_obj_set_width(ui_ImgButton10, 64);
    lv_obj_set_height(ui_ImgButton10, 64);
    lv_obj_set_x(ui_ImgButton10, -109);
    lv_obj_set_y(ui_ImgButton10, 179);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;
    ui_ImgButton8 = NULL;
    ui_ImgButton10 = NULL;

}
