// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_statusBar2;
extern lv_obj_t * ui_IconBuzzer2;
extern lv_obj_t * ui_iconRS2;
extern lv_obj_t * ui_iconNTP2;
extern lv_obj_t * ui_iconWIFI2;
extern lv_obj_t * ui_iconBT2;
extern lv_obj_t * ui_PercentBaterry2;
extern lv_obj_t * ui_Clock2;
extern lv_obj_t * ui_iconBATERRY2;
extern lv_obj_t * ui_Container3;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Dropdown1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

