// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: rf_tester

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    /* SquareLine UI init */
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Settings_screen_init();
    ui_CC1101_screen_init();
    ui_NRF24L01_screen_init();
    ui_LORA_screen_init();
    ui_RSSIPLOTTER_screen_init();
    ui_ABOUT_screen_init();
    ui_Screen8_screen_init();
    ui_Screen9_screen_init();
    ui_Screen10_screen_init();
    ui_MenuMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
}

void ui_destroy(void)
{
    ui_Settings_screen_destroy();
    ui_CC1101_screen_destroy();
    ui_NRF24L01_screen_destroy();
    ui_LORA_screen_destroy();
    ui_RSSIPLOTTER_screen_destroy();
    ui_ABOUT_screen_destroy();
    ui_Screen8_screen_destroy();
    ui_Screen9_screen_destroy();
    ui_Screen10_screen_destroy();
}
