// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project_menu_stm32h750

#ifndef _SQUARELINE_PROJECT_MENU_STM32H750_UI_H
#define _SQUARELINE_PROJECT_MENU_STM32H750_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MenuMain.h"
#include "screens/ui_Settings.h"
#include "screens/ui_CC1101.h"
#include "screens/ui_NRF24L01.h"
#include "screens/ui_LORA.h"
#include "screens/ui_RSSIPLOTTER.h"
#include "screens/ui_ABOUT.h"
#include "screens/ui_Screen8.h"
#include "screens/ui_Screen9.h"
#include "screens/ui_Screen10.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
