// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_menu_stm32h750

#include "ui.h"

void Apply_Settings_CC1101(lv_event_t * e)
{
	// Your code here
}
